/*
 * command_reference.h
 *
 *  Created on: Oct 18, 2025
 *      Author: tobias
 */

#ifndef COMMAND_REFERENCE_H_
#define COMMAND_REFERENCE_H_

typedef enum _control_byte_s {
	CONTROL_BYTE_IGNORE_CRC_BYTE = 1,
	CONTROL_BYTE_DONT_SEND_RESPONSE = 2
} control_byte_t;

typedef enum _ctia_status_s {
	CTIA_SUCCESS,
	CTIA_FAIL,
	CTIA_TOO_FEW_BYTES,
	CTIA_TOO_MANY_BYTES,
	CTIA_CRC_MISMATCH,
	CTIA_INVALID_CMD,
	CTIA_INVALID_PARAMETER,
	CTIA_TIMEOUT,
	CTIA_BUSY,
	CTIA_UNAVAILABLE
} ctia_status_t;

typedef enum _resp_cmd_s {
	RESP_OK	= 0x0101,
	RESP_ERROR,
	RESP_DEVICE_ID,
	RESP_DEVICE_NAME,
	RESP_SERIAL_NUMBER,
	RESP_FW_BUILD_DATE,
	RESP_FW_BUILD_TIME,
	RESP_FW_VERSION,
	RESP_AVAILABLE_MEAS_CH,
	RESP_AVAILABLE_STIM_CH,
	RESP_AVAILABLE_EXT_STIM_CH,
	RESP_BITFIELD_MEAS_H,
	RESP_BITFIELD_MEAS_L,
	RESP_BITFIELD_STIM,
	RESP_BITFIELD_EXT_STIM,
	RESP_EXT_PROBE_IN_STATE,
	RESP_ANALOG_BUS_DETECT_STATE,
	RESP_EXECUTE_SELFTEST,
	RESP_END = 0x01FF
} resp_cmd_t;

typedef enum _set_cmd_s {
	SET_EXCLUSIVE_MEAS_H_CH = 0x0201,
	SET_MEAS_H_CH,
	SET_BITFIELD_MEAS_H_CH,
	SET_EXCLUSIVE_MEAS_L_CH,
	SET_MEAS_L_CH,
	SET_BITFIELD_MEAS_L_CH,
	SET_EXCLUSIVE_STIM_CH,
	SET_STIM_CH,
	SET_BITFIELD_STIM_CH,
	SET_EXT_STIM_CH,
	SET_BITFIELD_EXT_STIM_CH,
	SET_EXT_PROBE_IN_STATE,
	SET_ANALOG_BUS_DETECT_STATE,
	SET_END = 0x02FF
} set_cmd_t;

typedef enum _clr_cmd_s {
	CLR_MEAS_H_CH = 0x0301,
	CLR_MEAS_H,
	CLR_MEAS_L_CH,
	CLR_MEAS_L,
	CLR_STIM_CH,
	CLR_STIM,
	CLR_EXT_STIM_CH,
	CLR_EXT_STIM,
	CLR_ALL_RELAYS,
	CLR_END = 0x03FF
} clr_cmd_t;

typedef enum _get_cmd_s {
	GET_DEVICE_ID = 0x0401,
	GET_DEVICE_NAME,
	GET_SERIAL_NUMBER,
	GET_FW_BUILD_DATE,
	GET_FW_BUILD_TIME,
	GET_FW_VERSION,
	GET_AVAILABLE_MEAS_CH,
	GET_AVAILABLE_STIM_CH,
	GET_AVAILABLE_EXT_STIM_CH,
	GET_BITFIELD_MEAS_H,
	GET_BITFIELD_MEAS_L,
	GET_BITFIELD_STIM,
	GET_BITFIELD_EXT_STIM,
	GET_EXT_PROBE_IN_STATE,
	GET_ANALOG_BUS_DETECT_STATE,
	GET_END = 0x04FF
} get_cmd_t;

typedef enum _conf_cmd_s {
	CONF_SERIAL_NUMBER = 0x0501,
	CONF_AVAILABLE_MEAS_CH,
	CONF_AVAILABLE_STIM_CH,
	CONF_AVAILABLE_EXT_STIM_CH,
	CONF_AVAILABLE_UART,
	CONF_AVAILABLE_I2C,
	CONF_AVAILABLE_RS485,
	CONF_END = 0x05FF
} conf_cmd_t;

typedef enum _exec_cmd_s {
	EXECUTE_SELFTEST = 0x0601,
	UART_TRANSMIT,
	EXEC_END = 0x06FF
} exec_cmd_t;

typedef enum _dbg_cmd_s {
	DBG_ENTER_BOOTLOADER = 0x0701,
	DBG_END = 0x07FF
} dbg_cmd_t;

#endif /* COMMAND_REFERENCE_H_ */
